
name: workflows
on:
  push:
    branches:
      - main

jobs:
  build_docker_image:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          echo "Generated image tag is ${{ github.sha }}" && ls
          docker build -t kunlekush/spring1:app-${{ github.sha }} -f ./Dockerfile .
          #docker build -t kunlekush/vue:webapp-${{ github.sha }} -f ./vue-test-app/Dockerfile ./vue-test-app
          echo "Docker build completed"

  push_image_to_registry:
    runs-on: self-hosted
    needs: build_docker_image
    steps:
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image to Registry
        run: docker push kunlekush/spring1:app-${{ github.sha }}

  deploy_to_dev:
    runs-on: self-hosted
    needs: push_image_to_registry
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email "kunlekush45@gmail.com"
          git config --global user.name "kunlekush"
          
      - name: Update Kubernetes Manifests
        run: |
          git clone https://${{ secrets.USERNAME_TOKEN}}:${{ secrets.PIPELINE_TOKEN }}@github.com/kun13kush/Mark2.git
          cd spring1 
          sed -i "s/spring1:app-.*/spring1:app-${{ github.sha }}/g" deployment.yaml
          cat deployment.yaml
          git add deployment.yaml
          git commit -m "Update spring test app Dev env k8s manifest file"
          git push origin main
